version: '3'

services: 

  web:
    # build: 
    #   context: ./docker/nginx
    image: nginx:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./src:/code
      - ./docker/nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - database
    networks: 
      - webnet

  php:
    #image: php:7-fpm
    build: ./docker/php
    volumes: 
      - ./src:/code
      - ./docker/php/conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks: 
      - webnet

  database:
    image: mariadb:latest
    build: ./docker/database
    environment:
      - MYSQL_DATABASE=smanagement
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes: 
      - ./docker/database/smanagment-schema.sql:/docker-entrypoint-initdb.d/mysql-dump.sql
    ports: 
      - "3306:3306"
    networks: 
      - webnet

networks:
  webnet: