version: '3'

services: 

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes: 
      - ../src:/code
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - app-network

  php:
    build: ./php 
    volumes: 
      - ../src:/code
      - ./php/conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks: 
      - app-network

  database:
    build: ./database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes: 
      - ./database/data.sql:/docker-entrypoint-initdb.d/mysql-dump.sql
    networks: 
      - app-network

networks:
  app-network:
    driver: bridge