version: '3'

services: 

  web:
    image: nginx:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    volumes: 
      - ../src:/code
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - webnet

  php:
    build: ./php 
    volumes: 
      - ../src:/code
      - ./php/conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks: 
      - webnet

  database:
    build: ./database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes: 
      - ./database/data.sql:/docker-entrypoint-initdb.d/mysql-dump.sql
    networks: 
      - webnet

networks:
  webnet: